### ISSUE TITLE
Enum List as input

### ISSUE THREAD

**Issue by alexcibotari** [graphql-java/graphql-java-tools#115]
Hello,

I have next GraphQL definition:
```
Query {
countries(regions: [Region!]): [Country!]
}

enum Region {
  EUROPE
  ASIA
}

type Country {
  code: String!
  name: String!
  regions: [Region!]
}
```
and Java
`
public Set<Country> getCountries(Set<RoamingRegion> regions)
`
or
`
public Set<Country> getCountries(Optional<Set<RoamingRegion>> regions)
`

when I do a request to GraphQL-Java i receive an error 

```
{
  "data": null,
  "errors": [
    {
      "message": "Validation error of type VariableTypeMismatch: Variable type doesn't match",
      "locations": [
        {
          "line": 2,
          "column": 43
        }
      ],
      "description": "Variable type doesn't match",
      "validationErrorType": "VariableTypeMismatch",
      "errorType": "ValidationError",
      "path": null,
      "extensions": null
    }
  ]
}
```

**UPDATE :**

```
query getCountries($regions: [Region]!) {
  countries(regions: $regions){
    code
    name
    regions
  }
}
```
as variables I send list of Regions as String because TypeScript automatically convert Array of Enums in to Array of Strings
```
['EUROPE','ASIA']
```

if I try the same but instead of List of Regions I use Single enum as input, everything works :(
This why I think problem is in List of Enums

**Comment by oliemansm** [comment]
I created a unit test to try to reproduce this issue. See `EnumListParameterSpec`. The problem is though, that this one succeeds successfully. 

I do notice the query you provide for testing doesn't match the schema above. More specifically in the schema you've defined the parameter `regions` of type `[Region!]`, while in the query you execute the type is `[Region]!`. The exclamation point is moved one position, but that will throw an error. Could it be that was causing this issue?

There were some other changes regarding enum input types today, so perhaps that solved this issue as well, although that seemed unrelated to be honest. Can you check my comments above and the unit test to see if you still face this issue or not?

**Comment by alexcibotari** [comment]
How you mentioned in your comment, the issue is in query. you can close .

**Comment by oliemansm** [comment]
Ok, thanks for your quick response.
