### ISSUE TITLE
More debugging data?

### ISSUE THREAD

**Issue by CH-EricLundberg** [graphql-java/graphql-java-tools#162]
Would it be possible to get a schema line number and/or parent object spit out when getting a FieldResolver error?  I currently have one that doesn't seem like it gives me much to go on:

```
Caused by: com.coxautodev.graphql.tools.FieldResolverError: No method or field found with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

  java.lang.String.code()
  java.lang.String.getCode()
  java.lang.String.code
```
Many objects in this schema have a ```code: String``` so trying to track down what is causing this is somewhat of a challenge. :)

**Comment by CH-EricLundberg** [comment]
Similarly it would be nice to be able to get more context around these errors: 

FieldResolverError: No method or field found with any of the following signatures 

I have a case where I have a com.company.Foo class, and the schema has a decorated version of that class with an additional computed field.  So I make something like com.company.graphql.FooDTO which extends the com.company.Foo class. I add a dictionary entry ("Foo",com.company.graphql.FooDTO.class) but I am getting a FieldResolverError for com.company.FOO.getDecorationBarList() when it should be looking at com.company.graphql.FooDTO.getDecorationBarList() and given the size of the schema and number of classes it is unclear if it because of the direct use of the 'Foo' in the schema, or if another object in the schema references the base class directly somewhere.

Which I guess would lead another question with the above scenario, if I also had a schema type

```
type Baz {
  theFoos: Foo
}
```

where Baz is a com.company.Baz object which has a list of com.company.Foo objects, will it use com.company.Foo or com.company.graphql.FooDTO I assume it will use the com.company.Foo object unless I create a com.company.graphql.BazDTO object which overloads theFoos to return the DTO version, but hard to tell.  Thoughts?

Or is making the DTO version extending the original the wrong approach and I should be doing something like 

```
public class FooResolver implements GraphQLResolver<Foo> { 

    public List<Bar> getDecorationBarList(Foo foo) {
           List<Bar> bars = doSomeStuff(foo);
           return bars;
    }
}
```

??

**Comment by oliemansm** [comment]
@CH-EricLundberg 
The original developer of this project is bogged down with other projects, and I'm not that familiar with this code base either yet unfortunately. Seems like you're facing a couple of issues here:

**Schema line number and/or parent object**
That sounds pretty annoying indeed and looking at the code, that could be improved easily. The parent of `FieldDefinition` has a `SourceLocation` containing the source name, line number and column. I'll add the source name and line number to the error message.

**Foo and FooDTO**
Sounds like your resolvers in some cases return `Foo` and in some cases use `FooDTO` as the type, while defined in the schema as `type Foo`. Do I understand you correctly here? Because I don't believe you can mix those. If you define a type in the schema you should use one class as its implementation everywhere. So if you are already using `Foo` somewhere, it will apparently disregard your `FooDTO` addition to the dictionary and just use the `Foo` class, resulting in this error.

I personally tend to use that `FooResolver` approach btw for returning (large) arrays, or complex objects. Especially if (a) it's part of the hierarchy in the graphql schema, but not in my domain model, or (b) if it contains complex objects with a large hierarchy of its own.

**Comment by CH-EricLundberg** [comment]
Schema line number: awesome!

Foo and FooDTO: I did work that out and see that using a resolver is the way to go with this.

**Comment by oliemansm** [comment]
Turned out to be a bit more complicated, since it was reading all provided resources into one large string and passing that one to graphql-java to be parsed. Thereby losing the binding with the correct files containing any errors. Refactored that now to include the correct information.
