### ISSUE TITLE
Exception with Scalar Date

### ISSUE THREAD

**Issue by elebeaup** [graphql-java/graphql-java-tools#52]
We are using OffsetDateTime field on our types and Graphql OffsetDateTime Scalar for mappring.

```
public class GraphQLDateType extends GraphQLScalarType {

  public GraphQLDateType() {

    super("Date", "Date", new Coercing<OffsetDateTime, String>() {

      DateTimeFormatter fmt = DateTimeFormatter.ISO_OFFSET_DATE_TIME;

      @Override
      public String serialize(Object input) {
        if (input instanceof OffsetDateTime) {
          return fmt.format((OffsetDateTime) input);
        } else {
          return null;
        }
      }

      @Override
      public OffsetDateTime parseValue(Object input) {
        if (input instanceof String) {
          return OffsetDateTime.from(fmt.parse((String) input));
        }
        return null;
      }

      @Override
      public OffsetDateTime parseLiteral(Object input) {
        if (input instanceof StringValue) {
          return OffsetDateTime.from(fmt.parse(((StringValue) input).getValue()));
        }
        return null;
      }
    });
  }
}
```

Queries are working fine.
Mutation do not work because Jackson (used by GraphQL Tools) cannot convert those OffsetDateTime fields.

GraphQL Tools uses its own instance of ObjectMapper (ResolverDataFetcher.kt). So we cannot load "JavaTimeModule()" on it to support OffsetDateTime.
(Jackson JSR310 dependency is loaded on our pom.xml but the module JavaTimeModule need to be registered to this instance of ObjectMapper)

It would be nice to export ObjectMapper in order to register Jackson data binding module.

**Comment by apottere** [comment]
I can definitely add a hook to update the objectmapper used.  Would you rather get the library's instance of the objectmapper and configure it, or provide your own and then have graphql-java-tools add it's own configuration (right now just the kotlin module)?

**Comment by apottere** [comment]
This is released in `4.0.1`, syncing now.  `SchemaParserOptions` has an option for providing an `objectMapperConfigurer` (functional interface).

**Comment by elebeaup** [comment]
Thanks a lot. This method should meet my needs.

**Comment by rolandkozma** [comment]
Hi,

It seems that I cannot get the configs right, so please help me. I created my OmniaObjectMapperConfigurer:

@Component
public class OmniaObjectMapperConfigurer implements ObjectMapperConfigurer {
    @Override
    public void configure(ObjectMapper mapper, ObjectMapperConfigurerContext context) {
        mapper.registerModule(new JavaTimeModule())
                .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
    }
}

Then in my config class I have:

@Configuration
public class GraphQLConfig {

    @Bean
    public SchemaParserOptions schemaParserOptions(OmniaObjectMapperConfigurer omniaObjectMapperConfigurer) {
        return SchemaParserOptions.newOptions()
                .objectMapperConfigurer(omniaObjectMapperConfigurer)
                .build();
    }

    @Bean
    public GraphQLLocalDate graphQLLocalDate() {
        return new GraphQLLocalDate();
    }
}

Unfortunately the object mapper settings still not work as expected. 
In GraphQLLocalDate, which extends GraphQLScalarType, the method:
 @Override public LocalDate parseValue(Object input)  -  from  Coercing<LocalDate, String>
receives an array as input (e.g. [2017, 10, 8]) while I think the input should be a String.

Regards,
- Roland

**Comment by rolandkozma** [comment]
Anyway, creating the LocalDate from the ArrayList of Integer that comes as intput to the parseValue method works, so I'm able to deserialize successfully. 
Actually I achieved the desired result, I just had wrong expectations from the Object input type, because I thought it have to be a String.

**Comment by rolandkozma** [comment]
The ArrayList of Integer was coming from my rest-assured tests which didn't had the object mapper configured with JavaTimeModule... So rest-assured serialized LocalDateTime as an ArrayList of Integer.
Making the query from graphiql works as expected and the input of the parseValue method is String.
Sorry for disturbing with a non-issue, the configs I posted actually work perfectly.

**Comment by apottere** [comment]
No worries, I'm glad you got it figured out.  Sorry I couldn't help sooner.

**Comment by alkismavridis** [comment]
I have the same issue, but unfortunatelly the proposed solution does not work in my case because I cannot locate the class JavaTimeModule that is mentioned.
I still cannot serialize scalar to LocalTime (I try to actually serialize it in secondOfDay() integer).

I have extended GraphQLScalarType, as mentioned above, but my **serialize** method is never called.

I was the one who convinced my team to switch from rest to graphQL, and I will have troubles if I dont find a solution for this issue.
So.. any help is really apreaciated.

**Comment by alkismavridis** [comment]
I have the same issue, but unfortunatelly the proposed solution does not work in my case because I cannot locate the class JavaTimeModule that is mentioned.
As a result, I cannot serialize my custom scalars to LocalTime (I actually use secondOfDay() / ofSecondOfDay() to convert LocalTimes to integers).

I have extended GraphQLScalarType, and thus, I have written the converting method that accepts a localTime and returns an int (Coercing.parseValue(Object input) and Coercing.parseLiteral(Object input)). The methods are indeed called and return successfully.
But my query fails with the message:

> Exception while fetching data (/saveReportTemplate) : Can not construct instance of java.time.LocalDate: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)

I wonder, should't the corresponding **Coercing.serialize(Object input)** being called?
I thought this is the purpose that this exists.
Did I get this wrong?

Any help is really apreaciated.
I was the one who convinced my team to switch from rest to graphQL and I was very enthousiastic about it, so I will have troubles if I dont find a solution for this issue.
